### ISSUE TITLE
Scheduler resuming everything instead of what was running before pausing 

### ISSUE THREAD

**Issue by Mr-Cake** [h3llrais3r/deluge-myscheduler#11]
To recreate pause a torrent manually and then have Scheduler change from paused state to running/throttled torrent will resume but should stay paused. To achieve behaviour of default plug-in.

https://github.com/h3llrais3r/deluge-myscheduler/issues/10#issuecomment-613195233

**Comment by h3llrais3r** [comment]
Stale issue.
