### ISSUE TITLE
Feature request: force start, in options menu as well.

### ISSUE THREAD

**Issue by matbor** [h3llrais3r/deluge-myscheduler#7]
Hi, thanks for the force start option, when you are working on the plugin again in the future can you add the 'force start' to the options menu as well. This would be handy for when using the web GUI on a device that you can't right click with. ie. iPad.

Example.

![img_0881](https://cloud.githubusercontent.com/assets/1978503/22365730/3ace3220-e4cd-11e6-817c-9f94ecc89ad8.PNG)

**Comment by h3llrais3r** [comment]
I'll see what I can do.

EDIT: but I think this should work on an ipad: hold your finger on an item you want to right click for a few seconds options available will pop up?

**Comment by h3llrais3r** [comment]
@matbor You gave me quite some work... 😄, but can you try it out with this version?
Option is located in general options tab.

![image](https://cloud.githubusercontent.com/assets/1945295/22407733/73362ab4-e66c-11e6-959e-8d9f82b43d1d.png)


[MyScheduler-0.3.6-py2.7.egg.zip](https://github.com/h3llrais3r/deluge-myscheduler/files/737795/MyScheduler-0.3.6-py2.7.egg.zip)

**Comment by matbor** [comment]
@h3llrais3r perfect. 

Seems to work nicely, tested on iOS and windows and works nicely.

**Comment by h3llrais3r** [comment]
Thanks for the feedback. I'll try to release asap. (Perhaps I still make some modifications 😉)
